#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
cd "$(dirname "$0")/.."
umask 077
ENV_FILE="$PWD/.env.release"
export GH_REPO=noelrohi/nowish
banner "Nowish release credentials"

stage "Apple notarization"
say "Your Developer ID certificate signs the app; notarization also needs Apple account access."
say "If you find an existing profile in Keychain Access, enter its name here."
ask NOTARY_PROFILE "Existing profile name (Enter to create nowish-release):"
if [[ -n "$NOTARY_PROFILE" ]]; then
  xcrun notarytool history --keychain-profile "$NOTARY_PROFILE" >/dev/null
  write_env NOTARY_PROFILE "$NOTARY_PROFILE"
else
  open_url "https://account.apple.com"
  step "Sign-In and Security → App-Specific Passwords → Generate an app-specific password."
  step "Name it Nowish releases. Use the Apple account enrolled in team 2Z79866758."
  ask APPLE_ID "Apple account email:"
  ask_secret APPLE_APP_SPECIFIC_PASSWORD "Paste the generated app-specific password (hidden):"
  [[ -n "$APPLE_ID" && -n "$APPLE_APP_SPECIFIC_PASSWORD" ]] || { warn "Both values are required."; exit 1; }
  NOTARY_PROFILE=nowish-release
  xcrun notarytool store-credentials "$NOTARY_PROFILE" --apple-id "$APPLE_ID" --password "$APPLE_APP_SPECIFIC_PASSWORD" --team-id 2Z79866758
  write_env NOTARY_PROFILE "$NOTARY_PROFILE"
  write_env APPLE_ID "$APPLE_ID"
fi
say "Notarization profile validated. Tell the agent the profile name to continue the local release."
if ! confirm "Also configure GitHub Actions for future releases now?"; then
  finish
  exit 0
fi
if [[ -z "${APPLE_APP_SPECIFIC_PASSWORD:-}" ]]; then
  open_url "https://account.apple.com"
  step "Sign-In and Security → App-Specific Passwords → Generate one for Nowish CI."
  ask APPLE_ID "Apple account email:"
  ask_secret APPLE_APP_SPECIFIC_PASSWORD "App-specific password for GitHub Actions (hidden):"
fi
[[ -n "$APPLE_ID" && -n "$APPLE_APP_SPECIFIC_PASSWORD" ]] || exit 1
xcrun notarytool store-credentials nowish-ci-setup --apple-id "$APPLE_ID" --password "$APPLE_APP_SPECIFIC_PASSWORD" --team-id 2Z79866758
set_secret APPLE_ID "$APPLE_ID"
set_secret APPLE_APP_SPECIFIC_PASSWORD "$APPLE_APP_SPECIFIC_PASSWORD"
unset APPLE_APP_SPECIFIC_PASSWORD

stage "Export the Developer ID identity"
open_url "https://help.apple.com/xcode/mac/current/#/dev8a2822e0b"
open -a 'Keychain Access'
step "In Keychain Access, select My Certificates and find Developer ID Application: Noel Garcia (2Z79866758)."
step "Choose the certificate with its private key, then File → Export Items. Save as .p12 outside this repository."
step "Protect the export with a new password. Approve the macOS export prompt."
ask CERTIFICATE_PATH "Full path to the exported .p12 file:"
[[ -f "$CERTIFICATE_PATH" ]] || { warn "File not found."; exit 1; }
ask_secret APPLE_CERTIFICATE_PASSWORD "Export password (hidden):"
[[ -n "$APPLE_CERTIFICATE_PASSWORD" ]] || exit 1
write_env CERTIFICATE_PATH "$CERTIFICATE_PATH"
set_secret APPLE_CERTIFICATE_BASE64 "$(base64 < "$CERTIFICATE_PATH" | tr -d '\n')"
set_secret APPLE_CERTIFICATE_PASSWORD "$APPLE_CERTIFICATE_PASSWORD"
unset APPLE_CERTIFICATE_PASSWORD

stage "Sparkle signing key"
say "Nowish already has an update signing key in this Mac’s Keychain."
say "We’ll copy it directly into a GitHub Actions secret without printing it."
ask SPARKLE_BIN "Sparkle bin directory (Enter uses /tmp/nowish-build/SourcePackages/artifacts/sparkle/Sparkle/bin):"
SPARKLE_BIN="${SPARKLE_BIN:-/tmp/nowish-build/SourcePackages/artifacts/sparkle/Sparkle/bin}"
[[ -x "$SPARKLE_BIN/generate_keys" ]] || { warn "Build Nowish first to download Sparkle tools."; exit 1; }
write_env SPARKLE_BIN "$SPARKLE_BIN"
PUBLIC_KEY=$("$SPARKLE_BIN/generate_keys" --account com.enru.nowish.sparkle -p)
[[ "$PUBLIC_KEY" == 'ITBjkXjmtfAscYEBVG9Ro/qJ+zTlj1Zx5kaEibbZIp0=' ]] || { warn "Wrong Sparkle key; refusing to replace CI credentials."; exit 1; }
SECRET_DIR=$(mktemp -d)
trap 'rm -rf "$SECRET_DIR"' EXIT
"$SPARKLE_BIN/generate_keys" --account com.enru.nowish.sparkle -x "$SECRET_DIR/sparkle.key" >/dev/null
set_secret SPARKLE_PRIVATE_KEY "$(cat "$SECRET_DIR/sparkle.key")"
rm -rf "$SECRET_DIR"
trap - EXIT
finish
say "Local notarization profile: $NOTARY_PROFILE"
say "No release is published by this wizard. Return to the agent to finish shipping."
